//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdpBroadcastCapture.Broadcast {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Temperatur", Namespace="http://schemas.datacontract.org/2004/07/ModtagBroadcastWcf")]
    [System.SerializableAttribute()]
    public partial class Temperatur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TempField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Temp {
            get {
                return this.TempField;
            }
            set {
                if ((object.ReferenceEquals(this.TempField, value) != true)) {
                    this.TempField = value;
                    this.RaisePropertyChanged("Temp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Broadcast.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostTempToList", ReplyAction="http://tempuri.org/IService1/PostTempToListResponse")]
        int PostTempToList(string temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostTempToList", ReplyAction="http://tempuri.org/IService1/PostTempToListResponse")]
        System.Threading.Tasks.Task<int> PostTempToListAsync(string temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTemps", ReplyAction="http://tempuri.org/IService1/GetAllTempsResponse")]
        UdpBroadcastCapture.Broadcast.Temperatur[] GetAllTemps();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTemps", ReplyAction="http://tempuri.org/IService1/GetAllTempsResponse")]
        System.Threading.Tasks.Task<UdpBroadcastCapture.Broadcast.Temperatur[]> GetAllTempsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UdpBroadcastCapture.Broadcast.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<UdpBroadcastCapture.Broadcast.IService1>, UdpBroadcastCapture.Broadcast.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int PostTempToList(string temp) {
            return base.Channel.PostTempToList(temp);
        }
        
        public System.Threading.Tasks.Task<int> PostTempToListAsync(string temp) {
            return base.Channel.PostTempToListAsync(temp);
        }
        
        public UdpBroadcastCapture.Broadcast.Temperatur[] GetAllTemps() {
            return base.Channel.GetAllTemps();
        }
        
        public System.Threading.Tasks.Task<UdpBroadcastCapture.Broadcast.Temperatur[]> GetAllTempsAsync() {
            return base.Channel.GetAllTempsAsync();
        }
    }
}
